"""
Generate a clean PDF from PRD-subagents-and-archetypes.md
Uses fpdf2 with Arial font.
Updated 2026-04-09: Supports expanded 7-archetype PRD.
"""

from fpdf import FPDF
import re

FONT_PATH = r"C:\Windows\Fonts\arial.ttf"
FONT_BOLD_PATH = r"C:\Windows\Fonts\arialbd.ttf"
FONT_MONO_PATH = r"C:\Windows\Fonts\consola.ttf"  # Consolas for monospace (Unicode)

INPUT_FILE = r"C:\Users\zlokl\edify-os\PRD-subagents-and-archetypes.md"
OUTPUT_FILE = r"C:\Users\zlokl\edify-os\PRD-subagents-and-archetypes.pdf"

MARGIN = 20
BODY_SIZE = 11
HEADER_SIZE = 14
TITLE_SIZE = 18
LINE_HEIGHT = 6
SECTION_SPACE = 4


class PRDDocument(FPDF):
    def __init__(self):
        super().__init__()
        self.add_font("Arial", "", FONT_PATH)
        self.add_font("Arial", "B", FONT_BOLD_PATH)
        self.add_font("Consolas", "", FONT_MONO_PATH)
        self.set_margins(MARGIN, MARGIN, MARGIN)
        self.set_auto_page_break(auto=True, margin=MARGIN)

    def header(self):
        # Minimal header -- just a thin line after page 1
        if self.page_no() > 1:
            self.set_font("Arial", "", 8)
            self.set_text_color(150, 150, 150)
            self.set_y(10)
            self.cell(0, 5, "PRD: Subagent System & Archetype Differentiation", align="L")
            self.ln(2)
            self.set_draw_color(200, 200, 200)
            self.line(MARGIN, self.get_y(), self.w - MARGIN, self.get_y())
            self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")
        self.set_text_color(0, 0, 0)

    def title_page(self):
        self.add_page()
        self.ln(40)

        # Title
        self.set_font("Arial", "B", TITLE_SIZE + 4)
        self.cell(0, 12, "PRD: Subagent System &", align="C", ln=True)
        self.cell(0, 12, "Archetype Differentiation", align="C", ln=True)
        self.ln(10)

        # Subtitle
        self.set_font("Arial", "", 13)
        self.cell(0, 8, "Whitmore Labs / Edify OS", align="C", ln=True)
        self.ln(6)

        # Divider line
        self.set_draw_color(80, 80, 80)
        mid_x = self.w / 2
        self.line(mid_x - 40, self.get_y(), mid_x + 40, self.get_y())
        self.ln(10)

        # Metadata block
        self.set_font("Arial", "", BODY_SIZE)
        meta_lines = [
            ("Generated by:", "Milo"),
            ("Date:", "2026-04-10"),
            ("Status:", "Draft (Updated 2026-04-09)"),
            ("Requested by:", "Z"),
            ("Archetypes:", "7"),
            ("Subagents:", "30"),
        ]
        col_w = 40
        for label, value in meta_lines:
            x = self.w / 2 - col_w
            self.set_x(x)
            self.set_font("Arial", "B", BODY_SIZE)
            self.cell(col_w, LINE_HEIGHT, label, ln=False)
            self.set_font("Arial", "", BODY_SIZE)
            self.cell(col_w + 20, LINE_HEIGHT, value, ln=True)


def safe_text(text):
    """Replace characters that might not render in Arial."""
    replacements = {
        "\u2014": "--",
        "\u2013": "-",
        "\u2019": "'",
        "\u2018": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "-",
        "\u2026": "...",
        "\u00e9": "e",
        "\u00e8": "e",
        "\u00e0": "a",
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def parse_inline(pdf, text, font_size, default_bold=False):
    """Render inline text with **bold** markers handled."""
    text = safe_text(text)
    parts = re.split(r"(\*\*[^*]+\*\*)", text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            inner = part[2:-2]
            pdf.set_font("Arial", "B", font_size)
            pdf.write(LINE_HEIGHT, inner)
        else:
            if default_bold:
                pdf.set_font("Arial", "B", font_size)
            else:
                pdf.set_font("Arial", "", font_size)
            pdf.write(LINE_HEIGHT, part)


def write_wrapped_line(pdf, text, font_size, bold=False):
    """Write a line with multi_cell for wrapping, handling inline bold."""
    text = safe_text(text)
    # If there's no inline bold, use multi_cell directly
    if "**" not in text:
        pdf.set_font("Arial", "B" if bold else "", font_size)
        pdf.multi_cell(0, LINE_HEIGHT, text)
    else:
        # Use write() for inline-bold lines (no auto-wrap on bold boundaries)
        parse_inline(pdf, text, font_size, default_bold=bold)
        pdf.ln()


def render_table(pdf, header, rows):
    """Render a simple bordered table with dynamic column sizing."""
    pdf.ln(3)
    eff_w = pdf.w - 2 * MARGIN
    num_cols = len(header)

    if num_cols <= 3:
        # 3 columns: fixed proportions
        col_widths = [
            int(eff_w * 0.28),
            int(eff_w * 0.32),
            int(eff_w * 0.40),
        ]
    elif num_cols <= 5:
        # Even distribution for 4-5 columns
        col_widths = [int(eff_w / num_cols)] * num_cols
    else:
        # Many columns (like the 7-archetype comparison table)
        # First column gets more space, rest split evenly
        first_col = int(eff_w * 0.15)
        remaining = eff_w - first_col
        rest_col = int(remaining / (num_cols - 1))
        col_widths = [first_col] + [rest_col] * (num_cols - 1)

    # Ensure we don't exceed page width
    total = sum(col_widths)
    if total > eff_w:
        scale = eff_w / total
        col_widths = [int(w * scale) for w in col_widths]

    def table_row(cells, bold=False):
        # Pad cells if fewer than columns
        while len(cells) < num_cols:
            cells.append("")

        # Calculate row height based on tallest cell
        max_lines = 1
        for i, cell in enumerate(cells):
            if i >= len(col_widths):
                break
            cell_text = safe_text(cell)
            chars_per_line = max(1, col_widths[i] / (BODY_SIZE * 0.45))
            lines = max(1, int(len(cell_text) / chars_per_line) + 1)
            max_lines = max(max_lines, lines)

        row_h = max_lines * (LINE_HEIGHT - 1) + 2

        x_start = pdf.get_x()
        y_start = pdf.get_y()

        # Check page break
        if y_start + row_h > pdf.h - MARGIN:
            pdf.add_page()
            y_start = pdf.get_y()
            x_start = pdf.get_x()

        for i, cell in enumerate(cells):
            if i >= len(col_widths):
                break
            pdf.set_xy(x_start + sum(col_widths[:i]), y_start)
            font_size = BODY_SIZE - 1 if num_cols <= 5 else BODY_SIZE - 2
            pdf.set_font("Arial", "B" if bold else "", font_size)
            pdf.multi_cell(col_widths[i], row_h / max_lines, safe_text(cell),
                          border=1, align="L")

        pdf.set_xy(x_start, y_start + row_h)

    # Header row
    table_row(header, bold=True)
    # Data rows
    for row in rows:
        table_row(row, bold=False)

    pdf.ln(3)


def render_code_block(pdf, lines):
    """Render a monospace code/file block with light indent."""
    pdf.ln(2)
    pdf.set_font("Consolas", "", BODY_SIZE - 2)
    indent = 4  # extra left indent in mm
    eff_w = pdf.w - 2 * MARGIN - indent

    for line in lines:
        text = safe_text(line)
        # Preserve indentation by using x offset
        pdf.set_x(MARGIN + indent)
        if len(text.strip()) == 0:
            pdf.ln(LINE_HEIGHT - 2)
        else:
            pdf.multi_cell(eff_w, LINE_HEIGHT - 1, text)
    pdf.ln(2)


def parse_and_render(pdf, content):
    """Parse markdown content and render to PDF."""
    lines = content.split("\n")
    i = 0

    while i < len(lines):
        line = lines[i]

        # --- Skip title / front matter (already on title page) ---
        if line.startswith("# PRD:") or (line.startswith("**") and any(
            kw in line for kw in ["Generated by", "Date:", "Status:", "Requested by:"]
        )):
            i += 1
            continue

        # --- Horizontal rule ---
        if line.strip() == "---":
            pdf.ln(2)
            pdf.set_draw_color(180, 180, 180)
            pdf.line(MARGIN, pdf.get_y(), pdf.w - MARGIN, pdf.get_y())
            pdf.ln(4)
            i += 1
            continue

        # --- H2 Section header ---
        if line.startswith("## "):
            text = line[3:].strip()
            pdf.ln(SECTION_SPACE)
            pdf.set_font("Arial", "B", HEADER_SIZE)
            pdf.multi_cell(0, 8, safe_text(text))
            pdf.ln(2)
            # Underline
            pdf.set_draw_color(80, 80, 80)
            y = pdf.get_y()
            pdf.line(MARGIN, y, MARGIN + 80, y)
            pdf.ln(4)
            i += 1
            continue

        # --- H3 Sub-header ---
        if line.startswith("### "):
            text = line[4:].strip()
            pdf.ln(2)
            pdf.set_font("Arial", "B", BODY_SIZE + 1)
            pdf.multi_cell(0, LINE_HEIGHT, safe_text(text))
            pdf.ln(2)
            i += 1
            continue

        # --- Table detection ---
        if line.startswith("|"):
            table_lines = []
            while i < len(lines) and lines[i].startswith("|"):
                table_lines.append(lines[i])
                i += 1

            # Parse table
            header = []
            rows = []
            for ti, tl in enumerate(table_lines):
                cells = [c.strip() for c in tl.strip("|").split("|")]
                if ti == 0:
                    header = cells
                elif re.match(r"^[-| :]+$", tl.replace("|", "").replace(" ", "").replace("-", "").replace(":", "")):
                    continue  # separator row
                elif all(re.match(r"^-+$", c.strip()) for c in cells if c.strip()):
                    continue
                else:
                    # Check if it's a separator line
                    cleaned = tl.replace("|", "").replace("-", "").replace(":", "").replace(" ", "")
                    if not cleaned:
                        continue
                    rows.append(cells)

            render_table(pdf, header, rows)
            continue

        # --- Code block detection ---
        if line.strip().startswith("```"):
            i += 1
            code_lines = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            render_code_block(pdf, code_lines)
            continue

        # --- Checkbox / task list item ---
        if line.strip().startswith("- [ ]") or line.strip().startswith("- [x]"):
            indent_level = len(line) - len(line.lstrip())
            checked = "[x]" in line
            text = re.sub(r"- \[[ x]\] ", "", line.strip())
            mark = "[x]" if checked else "[ ]"
            x_indent = MARGIN + (indent_level / 4) * 4 + 2
            pdf.set_x(x_indent)
            pdf.set_font("Arial", "", BODY_SIZE)
            pdf.multi_cell(0, LINE_HEIGHT, safe_text(f"{mark} {text}"))
            i += 1
            continue

        # --- Bullet point ---
        if re.match(r"^(\s*)[-*] ", line):
            indent_match = re.match(r"^(\s*)", line)
            indent_spaces = len(indent_match.group(1)) if indent_match else 0
            indent_mm = MARGIN + 4 + (indent_spaces / 4) * 8
            text = re.sub(r"^\s*[-*] ", "", line)

            pdf.set_x(indent_mm)
            # bullet character
            pdf.set_font("Arial", "", BODY_SIZE)
            pdf.cell(4, LINE_HEIGHT, "-")
            # text (with inline bold support)
            avail_w = pdf.w - indent_mm - 4 - MARGIN
            if "**" not in text:
                pdf.set_font("Arial", "", BODY_SIZE)
                pdf.multi_cell(0, LINE_HEIGHT, safe_text(text))
            else:
                parse_inline(pdf, text, BODY_SIZE)
                pdf.ln()
            i += 1
            continue

        # --- Numbered list item ---
        if re.match(r"^\d+\. ", line):
            text = re.sub(r"^\d+\. ", "", line)
            num = re.match(r"^(\d+)\.", line).group(1)
            indent_mm = MARGIN + 6
            pdf.set_x(indent_mm)
            pdf.set_font("Arial", "B", BODY_SIZE)
            pdf.cell(6, LINE_HEIGHT, f"{num}.")
            avail_w = pdf.w - indent_mm - 6 - MARGIN
            if "**" not in text:
                pdf.set_font("Arial", "", BODY_SIZE)
                pdf.multi_cell(0, LINE_HEIGHT, safe_text(text))
            else:
                parse_inline(pdf, text, BODY_SIZE)
                pdf.ln()
            i += 1
            continue

        # --- Bold-only line (standalone **text:**) ---
        if line.strip().startswith("**") and line.strip().endswith("**") and line.strip().count("**") == 2:
            text = line.strip()[2:-2]
            pdf.set_font("Arial", "B", BODY_SIZE)
            pdf.multi_cell(0, LINE_HEIGHT, safe_text(text))
            i += 1
            continue

        # --- Z Approval line ---
        if line.startswith("**Z Approval:**") or line.startswith("**Z's notes:**"):
            pdf.set_font("Arial", "B", BODY_SIZE)
            text = safe_text(line.replace("**", ""))
            pdf.multi_cell(0, LINE_HEIGHT, text)
            i += 1
            continue

        # --- Empty line ---
        if line.strip() == "":
            pdf.ln(LINE_HEIGHT - 2)
            i += 1
            continue

        # --- Normal paragraph text (may have inline bold) ---
        if line.strip():
            write_wrapped_line(pdf, line.strip(), BODY_SIZE)
            i += 1
            continue

        i += 1


def main():
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    pdf = PRDDocument()
    pdf.set_title("PRD: Subagent System & Archetype Differentiation")
    pdf.set_author("Whitmore Labs / Edify OS")

    # Title page
    pdf.title_page()

    # Content pages
    pdf.add_page()
    parse_and_render(pdf, content)

    pdf.output(OUTPUT_FILE)
    print(f"PDF created: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
