"use client";

import { useState } from "react";
import {
  Search,
  Plus,
  Pencil,
  Trash2,
  X,
  Heart,
  BookOpen,
  Users,
  Gift,
  Megaphone,
  Palette,
  UserCircle,
  Cog,
  HelpCircle,
} from "lucide-react";

type MemoryCategory =
  | "mission"
  | "programs"
  | "donors"
  | "grants"
  | "campaigns"
  | "brand_voice"
  | "contacts"
  | "processes"
  | "general";

interface MemoryEntry {
  id: string;
  category: MemoryCategory;
  title: string;
  content: string;
  source: string | null;
  autoGenerated: boolean;
  updatedAt: string;
}

const categoryConfig: Record<
  MemoryCategory,
  { label: string; icon: typeof Heart }
> = {
  mission: { label: "Mission", icon: Heart },
  programs: { label: "Programs", icon: BookOpen },
  donors: { label: "Donors", icon: Users },
  grants: { label: "Grants", icon: Gift },
  campaigns: { label: "Campaigns", icon: Megaphone },
  brand_voice: { label: "Brand Voice", icon: Palette },
  contacts: { label: "Contacts", icon: UserCircle },
  processes: { label: "Processes", icon: Cog },
  general: { label: "General", icon: HelpCircle },
};

const entries: MemoryEntry[] = [
  {
    id: "1",
    category: "mission",
    title: "Organization Mission",
    content:
      "Hope Community Foundation empowers underserved communities through education, mentorship, and sustainable development programs. Founded in 2010, we serve over 5,000 families annually across three counties.",
    source: null,
    autoGenerated: false,
    updatedAt: "2 days ago",
  },
  {
    id: "2",
    category: "programs",
    title: "Youth Mentoring Program",
    content:
      "Our flagship program matches at-risk youth ages 12-18 with trained adult mentors. Currently serving 200 youth with a 90% program completion rate.",
    source: null,
    autoGenerated: false,
    updatedAt: "1 week ago",
  },
  {
    id: "3",
    category: "programs",
    title: "Community Garden Initiative",
    content:
      "Urban farming program providing fresh produce to food deserts. Operates 12 community gardens across the service area.",
    source: null,
    autoGenerated: false,
    updatedAt: "1 week ago",
  },
  {
    id: "4",
    category: "brand_voice",
    title: "Brand Guidelines",
    content:
      "Tone: Warm, hopeful, professional. Avoid jargon. Use people-first language. Always center community voices in our storytelling.",
    source: null,
    autoGenerated: false,
    updatedAt: "3 days ago",
  },
  {
    id: "5",
    category: "donors",
    title: "Major Donor - Johnson Family",
    content:
      "Annual giving: $25,000. Primary interest: Youth programs. Contact: Sarah Johnson, sjohnson@email.com. Last interaction: March 2026 gala.",
    source: "CRM Import",
    autoGenerated: true,
    updatedAt: "1 day ago",
  },
];

export default function MemoryPage() {
  const [activeCategory, setActiveCategory] = useState<MemoryCategory | "all">(
    "all"
  );
  const [search, setSearch] = useState("");
  const [showAddForm, setShowAddForm] = useState(false);
  const [newEntry, setNewEntry] = useState({
    title: "",
    content: "",
    category: "general" as MemoryCategory,
  });

  const categories = Object.entries(categoryConfig) as [
    MemoryCategory,
    (typeof categoryConfig)[MemoryCategory]
  ][];

  const filtered = entries.filter((e) => {
    if (activeCategory !== "all" && e.category !== activeCategory) return false;
    if (
      search &&
      !e.title.toLowerCase().includes(search.toLowerCase()) &&
      !e.content.toLowerCase().includes(search.toLowerCase())
    )
      return false;
    return true;
  });

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="heading-1">Organization Memory</h1>
          <p className="mt-1 text-slate-500">
            The knowledge base your AI team uses to stay context-aware.
          </p>
        </div>
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="btn-primary"
        >
          <Plus className="h-4 w-4" />
          Add Entry
        </button>
      </div>

      {/* Add Form */}
      {showAddForm && (
        <div className="card p-5 animate-slide-up">
          <div className="flex items-center justify-between mb-4">
            <h3 className="heading-3">New Memory Entry</h3>
            <button
              onClick={() => setShowAddForm(false)}
              className="text-slate-400 hover:text-slate-600"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
          <div className="grid gap-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="label mb-1.5 block">Title</label>
                <input
                  type="text"
                  value={newEntry.title}
                  onChange={(e) =>
                    setNewEntry({ ...newEntry, title: e.target.value })
                  }
                  className="input-field"
                  placeholder="Entry title..."
                />
              </div>
              <div>
                <label className="label mb-1.5 block">Category</label>
                <select
                  value={newEntry.category}
                  onChange={(e) =>
                    setNewEntry({
                      ...newEntry,
                      category: e.target.value as MemoryCategory,
                    })
                  }
                  className="input-field"
                >
                  {categories.map(([key, config]) => (
                    <option key={key} value={key}>
                      {config.label}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <div>
              <label className="label mb-1.5 block">Content</label>
              <textarea
                value={newEntry.content}
                onChange={(e) =>
                  setNewEntry({ ...newEntry, content: e.target.value })
                }
                className="input-field"
                rows={4}
                placeholder="What should your AI team know..."
              />
            </div>
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setShowAddForm(false)}
                className="btn-secondary"
              >
                Cancel
              </button>
              <button className="btn-primary">Save Entry</button>
            </div>
          </div>
        </div>
      )}

      {/* Search */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
        <input
          type="text"
          placeholder="Search memory..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="input-field pl-9"
        />
      </div>

      {/* Category Tabs */}
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => setActiveCategory("all")}
          className={`rounded-lg px-3 py-1.5 text-sm font-medium transition-all ${
            activeCategory === "all"
              ? "bg-brand-500 text-white shadow-sm"
              : "bg-slate-100 text-slate-600 hover:bg-slate-200"
          }`}
        >
          All
        </button>
        {categories.map(([key, config]) => {
          const count = entries.filter((e) => e.category === key).length;
          return (
            <button
              key={key}
              onClick={() => setActiveCategory(key)}
              className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-all ${
                activeCategory === key
                  ? "bg-brand-500 text-white shadow-sm"
                  : "bg-slate-100 text-slate-600 hover:bg-slate-200"
              }`}
            >
              <config.icon className="h-3.5 w-3.5" />
              {config.label}
              {count > 0 && (
                <span
                  className={`text-xs ${
                    activeCategory === key
                      ? "text-white/70"
                      : "text-slate-400"
                  }`}
                >
                  {count}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* Entries */}
      <div className="space-y-3">
        {filtered.length === 0 ? (
          <div className="card p-12 text-center">
            <Search className="mx-auto h-8 w-8 text-slate-300" />
            <p className="mt-3 text-sm text-slate-500">No entries found.</p>
          </div>
        ) : (
          filtered.map((entry) => {
            const catConfig = categoryConfig[entry.category];
            return (
              <div key={entry.id} className="card p-5 group">
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-3 min-w-0">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-brand-50">
                      <catConfig.icon className="h-4 w-4 text-brand-500" />
                    </div>
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <h3 className="font-semibold text-slate-900">
                          {entry.title}
                        </h3>
                        {entry.autoGenerated && (
                          <span className="rounded-full bg-brand-50 px-2 py-0.5 text-xs font-medium text-brand-600">
                            AI Generated
                          </span>
                        )}
                      </div>
                      <p className="mt-1 text-sm text-slate-600 leading-relaxed">
                        {entry.content}
                      </p>
                      <div className="mt-2 flex items-center gap-3 text-xs text-slate-400">
                        <span>{catConfig.label}</span>
                        {entry.source && (
                          <>
                            <span>From: {entry.source}</span>
                          </>
                        )}
                        <span>Updated {entry.updatedAt}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex shrink-0 gap-1 opacity-0 group-hover:opacity-100 transition-opacity ml-4">
                    <button className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600">
                      <Pencil className="h-4 w-4" />
                    </button>
                    <button className="rounded-lg p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-500">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
