import { NextRequest, NextResponse } from "next/server";
import { createServiceRoleClient, getAuthContext } from "@/lib/supabase/server";
import type { MemoryEntryCategory, MemoryEntryRow } from "@/app/api/memory/entries/route";

const VALID_CATEGORIES: MemoryEntryCategory[] = [
  "mission", "programs", "donors", "grants", "campaigns",
  "brand_voice", "contacts", "processes", "general",
  "financials", "volunteers", "events",
];

/**
 * PATCH /api/memory/entries/[id]
 * Updates fields on a user-created memory entry.
 * Auto-generated entries are read-only from this UI.
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { user, orgId } = await getAuthContext();
  if (!user || !orgId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const serviceClient = createServiceRoleClient();
  if (!serviceClient) {
    return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  }

  const { id } = await params;

  // Verify the entry exists and belongs to this org
  const { data: existing, error: fetchError } = await serviceClient
    .from("memory_entries")
    .select("id, org_id, auto_generated")
    .eq("id", id)
    .eq("org_id", orgId)
    .single();

  if (fetchError || !existing) {
    return NextResponse.json({ error: "Entry not found" }, { status: 404 });
  }

  if (existing.auto_generated) {
    return NextResponse.json(
      { error: "This entry is system-generated and cannot be edited." },
      { status: 403 }
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { category, title, content, source } = body as {
    category?: unknown;
    title?: unknown;
    content?: unknown;
    source?: unknown;
  };

  const updates: Record<string, unknown> = {};

  if (category !== undefined) {
    if (!VALID_CATEGORIES.includes(category as MemoryEntryCategory)) {
      return NextResponse.json({ error: "Invalid category" }, { status: 400 });
    }
    updates.category = category;
  }
  if (title !== undefined) {
    if (typeof title !== "string" || title.trim().length === 0) {
      return NextResponse.json({ error: "title must be a non-empty string" }, { status: 400 });
    }
    updates.title = title.trim();
  }
  if (content !== undefined) {
    if (typeof content !== "string" || content.trim().length === 0) {
      return NextResponse.json({ error: "content must be a non-empty string" }, { status: 400 });
    }
    updates.content = content.trim();
  }
  if (source !== undefined) {
    updates.source = source && typeof source === "string" ? source.trim() || null : null;
  }

  if (Object.keys(updates).length === 0) {
    return NextResponse.json({ error: "No fields to update" }, { status: 400 });
  }

  const { data: updated, error: updateError } = await serviceClient
    .from("memory_entries")
    .update(updates)
    .eq("id", id)
    .eq("org_id", orgId)
    .select("id, category, title, content, source, auto_generated, updated_at")
    .single();

  if (updateError || !updated) {
    return NextResponse.json({ error: updateError?.message ?? "Update failed" }, { status: 500 });
  }

  const row: MemoryEntryRow = {
    id: updated.id as string,
    category: updated.category as MemoryEntryCategory,
    title: updated.title as string,
    content: updated.content as string,
    source: (updated.source as string | null) ?? null,
    autoGenerated: (updated.auto_generated as boolean) ?? false,
    updatedAt: updated.updated_at as string,
  };

  return NextResponse.json(row);
}

/**
 * DELETE /api/memory/entries/[id]
 * Deletes a user-created memory entry.
 * Auto-generated entries are read-only from this UI.
 */
export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { user, orgId } = await getAuthContext();
  if (!user || !orgId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const serviceClient = createServiceRoleClient();
  if (!serviceClient) {
    return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  }

  const { id } = await params;

  // Verify the entry exists, belongs to this org, and is not auto-generated
  const { data: existing, error: fetchError } = await serviceClient
    .from("memory_entries")
    .select("id, org_id, auto_generated")
    .eq("id", id)
    .eq("org_id", orgId)
    .single();

  if (fetchError || !existing) {
    return NextResponse.json({ error: "Entry not found" }, { status: 404 });
  }

  if (existing.auto_generated) {
    return NextResponse.json(
      { error: "This entry is system-generated and cannot be deleted." },
      { status: 403 }
    );
  }

  const { error: deleteError } = await serviceClient
    .from("memory_entries")
    .delete()
    .eq("id", id)
    .eq("org_id", orgId);

  if (deleteError) {
    return NextResponse.json({ error: deleteError.message }, { status: 500 });
  }

  return new NextResponse(null, { status: 204 });
}
