import { NextRequest, NextResponse } from "next/server";
import { createServiceRoleClient, getAuthContext } from "@/lib/supabase/server";

export type MemoryEntryCategory =
  | "mission"
  | "programs"
  | "donors"
  | "grants"
  | "campaigns"
  | "brand_voice"
  | "contacts"
  | "processes"
  | "general"
  | "financials"
  | "volunteers"
  | "events";

export type MemoryEntrySource = "memory_entries" | "org_mission" | "document" | "archetype_name";

export interface MemoryEntryRow {
  id: string;
  category: MemoryEntryCategory;
  title: string;
  content: string;
  source: string | null;
  autoGenerated: boolean;
  updatedAt: string;
}

export async function GET() {
  const { user, orgId } = await getAuthContext();
  if (!user || !orgId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const serviceClient = createServiceRoleClient();
  if (!serviceClient) {
    return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  }

  const entries: MemoryEntryRow[] = [];

  // 1. Org mission (from orgs table)
  const { data: org } = await serviceClient
    .from("orgs")
    .select("mission, updated_at")
    .eq("id", orgId)
    .single();

  if (org?.mission) {
    entries.push({
      id: `org-mission-${orgId}`,
      category: "mission",
      title: "Organization Mission",
      content: org.mission,
      source: "Org Settings",
      autoGenerated: false,
      updatedAt: org.updated_at as string,
    });
  }

  // 2. Uploaded documents
  const { data: docs } = await serviceClient
    .from("documents")
    .select("id, file_name, category, parsed_text, created_at")
    .eq("org_id", orgId)
    .eq("processing_status", "done")
    .order("created_at", { ascending: false })
    .limit(20);

  for (const doc of docs ?? []) {
    const categoryMap: Record<string, MemoryEntryCategory> = {
      strategic_plan: "processes",
      grant_proposal: "grants",
      donor_list: "donors",
      financial_statement: "general",
      program_description: "programs",
      marketing_materials: "campaigns",
      event_plan: "general",
      staff_roster: "contacts",
      board_documents: "processes",
      other: "general",
    };
    entries.push({
      id: `doc-${doc.id}`,
      category: categoryMap[doc.category as string] ?? "general",
      title: doc.file_name as string,
      content: ((doc.parsed_text as string) ?? "").slice(0, 500) || "No content extracted.",
      source: "Uploaded Document",
      autoGenerated: true,
      updatedAt: doc.created_at as string,
    });
  }

  // 3. Custom archetype names from members
  const { data: members } = await serviceClient
    .from("members")
    .select("archetype_names")
    .eq("org_id", orgId);

  const seenSlugs = new Set<string>();
  for (const member of members ?? []) {
    const names = (member.archetype_names ?? {}) as Record<string, string>;
    for (const [slug, name] of Object.entries(names)) {
      if (name && !seenSlugs.has(slug)) {
        seenSlugs.add(slug);
        entries.push({
          id: `archetype-name-${slug}`,
          category: "general",
          title: `Custom Name: ${slug.replace(/_/g, " ")}`,
          content: `This team member is called "${name}" instead of their default role title.`,
          source: "Team Settings",
          autoGenerated: false,
          updatedAt: new Date().toISOString(),
        });
      }
    }
  }

  // 4. Memory entries from the memory_entries table
  const { data: memEntries } = await serviceClient
    .from("memory_entries")
    .select("id, category, title, content, source, auto_generated, updated_at")
    .eq("org_id", orgId)
    .order("updated_at", { ascending: false })
    .limit(50);

  for (const me of memEntries ?? []) {
    entries.push({
      id: me.id as string,
      category: me.category as MemoryEntryCategory,
      title: me.title as string,
      content: me.content as string,
      source: (me.source as string | null) ?? null,
      autoGenerated: (me.auto_generated as boolean) ?? false,
      updatedAt: me.updated_at as string,
    });
  }

  return NextResponse.json(entries);
}

export async function POST(request: NextRequest) {
  const { user, orgId, memberId } = await getAuthContext();
  if (!user || !orgId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const serviceClient = createServiceRoleClient();
  if (!serviceClient) {
    return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { category, title, content, source } = body as {
    category?: unknown;
    title?: unknown;
    content?: unknown;
    source?: unknown;
  };

  const validCategories: MemoryEntryCategory[] = [
    "mission", "programs", "donors", "grants", "campaigns",
    "brand_voice", "contacts", "processes", "general",
    "financials", "volunteers", "events",
  ];

  if (!category || !validCategories.includes(category as MemoryEntryCategory)) {
    return NextResponse.json({ error: "Invalid or missing category" }, { status: 400 });
  }
  if (!title || typeof title !== "string" || title.trim().length === 0) {
    return NextResponse.json({ error: "title is required" }, { status: 400 });
  }
  if (!content || typeof content !== "string" || content.trim().length === 0) {
    return NextResponse.json({ error: "content is required" }, { status: 400 });
  }

  const { data: inserted, error: insertError } = await serviceClient
    .from("memory_entries")
    .insert({
      org_id: orgId,
      category: category as MemoryEntryCategory,
      title: (title as string).trim(),
      content: (content as string).trim(),
      source: source && typeof source === "string" ? source.trim() || null : null,
      created_by: memberId ?? undefined,
      auto_generated: false,
    })
    .select("id, category, title, content, source, auto_generated, updated_at")
    .single();

  if (insertError || !inserted) {
    return NextResponse.json({ error: insertError?.message ?? "Insert failed" }, { status: 500 });
  }

  const entry: MemoryEntryRow = {
    id: inserted.id as string,
    category: inserted.category as MemoryEntryCategory,
    title: inserted.title as string,
    content: inserted.content as string,
    source: (inserted.source as string | null) ?? null,
    autoGenerated: (inserted.auto_generated as boolean) ?? false,
    updatedAt: inserted.updated_at as string,
  };

  return NextResponse.json(entry, { status: 201 });
}
