-- Migration 00026: Storage bucket for rendered design PNGs
--
-- Context: render_design_to_image generates PNGs server-side and was uploading
-- them to Anthropic's Files API. Per Anthropic's docs, files uploaded by the
-- API key are NOT downloadable — the Files API allows downloads only for
-- files generated by skills / code execution. So calls to /api/files/{fileId}
-- for rendered PNGs returned 400 "is not downloadable".
--
-- Fix: store rendered PNGs in Supabase Storage instead. The new
-- /api/renders/[renderId] endpoint authenticates the requester and streams
-- the bytes back. Bucket is private (no anon access); the service role
-- client bypasses RLS for both upload and download.
--
-- Path scheme inside the bucket: <orgId>/<renderId>.png
-- This isolates one tenant's renders from another and lets us enforce
-- "you can only download renders from your own org" cheaply at the API
-- layer (the path embeds the org_id).

INSERT INTO storage.buckets (id, name, public)
VALUES ('rendered-files', 'rendered-files', false)
ON CONFLICT (id) DO NOTHING;
