/**
 * Plugin skill registry — maps each archetype to the skill_ids uploaded from
 * Anthropic's open-source knowledge-work-plugins via the Skills API.
 *
 * These are DISTINCT from the pre-built Anthropic skills ("docx", "xlsx", etc.)
 * in lib/skills/registry.ts. Plugin skill_ids are dynamic: they are generated by
 * scripts/upload-plugin-skills.ts and stored in apps/web/plugins/uploaded-ids.json.
 *
 * How to add a new plugin skill to an archetype:
 *   1. Copy the skill directory into apps/web/plugins/<domain>/<skill>/
 *   2. Run `pnpm --filter web upload-plugin-skills` to get a skill_id.
 *   3. Add the key to the archetype mapping below.
 *
 * The ARCHETYPE_PLUGIN_SKILLS map is merged into the container.skill_ids param
 * in lib/chat/run-archetype-turn.ts alongside the pre-built skill IDs.
 */

import type { ArchetypeSlug } from "@/lib/archetypes";
// Cast to Record so we can look up arbitrary plugin keys (e.g. "marketing/content-creation")
// without TypeScript complaining about missing properties on the initially-empty JSON.
import uploadedIdsRaw from "../../../plugins/uploaded-ids.json";
const uploadedIds = uploadedIdsRaw as Record<string, string | undefined>;

/**
 * Archetype → uploaded plugin skill_ids.
 *
 * Values are filtered at runtime: if a skill has not been uploaded yet (no entry
 * in uploaded-ids.json), it is silently excluded rather than sending an invalid ID.
 *
 * Follow-on sprints populate the other archetypes.
 */
export const ARCHETYPE_PLUGIN_SKILLS: Record<ArchetypeSlug, string[]> = {
  marketing_director: [uploadedIds["marketing/content-creation"]].filter(Boolean) as string[],

  // Remaining archetypes: empty for Sprint 1 — populated in follow-on sprints.
  executive_assistant: [],
  events_director: [],
  development_director: [],
  programs_director: [],
  hr_volunteer_coordinator: [],
};
