/**
 * Plugin skill registry — maps each archetype to the skill_ids uploaded from
 * Anthropic's open-source knowledge-work-plugins via the Skills API.
 *
 * These are DISTINCT from the pre-built Anthropic skills ("docx", "xlsx", etc.)
 * in lib/skills/registry.ts. Plugin skill_ids are dynamic: they are generated by
 * scripts/upload-plugin-skills.ts and stored in apps/web/plugins/uploaded-ids.json.
 *
 * How to add a new plugin skill to an archetype:
 *   1. Copy the skill directory into apps/web/plugins/<domain>/<skill>/
 *   2. Run `pnpm --filter web upload-plugin-skills` to get a skill_id.
 *   3. Add the key to the archetype mapping below.
 *
 * The ARCHETYPE_PLUGIN_SKILLS map is merged into the container.skill_ids param
 * in lib/chat/run-archetype-turn.ts alongside the pre-built skill IDs.
 */

import type { ArchetypeSlug } from "@/lib/archetypes";
// Cast to Record so we can look up arbitrary plugin keys (e.g. "marketing/content-creation")
// without TypeScript complaining about missing properties on the initially-empty JSON.
// Each entry is an object { skill_id, hash, uploaded_at } — use .skill_id to extract the ID.
import uploadedIdsRaw from "../../../plugins/uploaded-ids.json";
const uploadedIds = uploadedIdsRaw as Record<
  string,
  { skill_id: string; hash: string; uploaded_at: string } | undefined
>;

/** Resolve a plugin key → skill_id string (or undefined if not yet uploaded). */
function resolve(key: string): string | undefined {
  return uploadedIds[key]?.skill_id;
}

/**
 * Archetype → uploaded plugin skill_ids.
 *
 * Values are filtered at runtime: if a skill has not been uploaded yet (no entry
 * in uploaded-ids.json), it is silently excluded rather than sending an invalid ID.
 *
 * Follow-on sprints populate the other archetypes.
 */
export const ARCHETYPE_PLUGIN_SKILLS: Record<ArchetypeSlug, string[]> = {
  marketing_director: [
    resolve("marketing/content-creation"),
    resolve("marketing/campaign-plan"),
    resolve("marketing/draft-content"),
    resolve("marketing/brand-review"),
    resolve("design/design-critique"),
    resolve("design/canvas-design"),
    resolve("design/theme-factory"),
    resolve("design/social_card"),
    resolve("design/flyer"),
    resolve("design/donor_thank_you"),
    resolve("design/gala_invite"),
  ].filter(Boolean) as string[],

  // Remaining archetypes: empty for Sprint 1 — populated in follow-on sprints.
  executive_assistant: [],
  events_director: [],
  development_director: [],
  programs_director: [],
  hr_volunteer_coordinator: [
    resolve("human-resources/onboarding"),
    resolve("human-resources/interview-prep"),
    resolve("human-resources/performance-review"),
    resolve("human-resources/policy-lookup"),
    resolve("human-resources/comp-analysis"),
    resolve("human-resources/volunteer_recruitment_kit"),
    resolve("human-resources/recognition_program"),
    resolve("human-resources/volunteer_handbook_section"),
    resolve("document/docx"),
    resolve("document/xlsx"),
  ].filter(Boolean) as string[],
};
