/**
 * Plugin skill registry — maps each archetype to the skill_ids uploaded from
 * Anthropic's open-source knowledge-work-plugins via the Skills API.
 *
 * These are DISTINCT from the pre-built Anthropic skills ("docx", "xlsx", etc.)
 * in lib/skills/registry.ts. Plugin skill_ids are dynamic: they are generated by
 * scripts/upload-plugin-skills.ts and stored in apps/web/plugins/uploaded-ids.json.
 *
 * How to add a new plugin skill to an archetype:
 *   1. Copy the skill directory into apps/web/plugins/<domain>/<skill>/
 *   2. Run `pnpm --filter web upload-plugin-skills` to get a skill_id.
 *   3. Add the key to the archetype mapping below.
 *
 * The ARCHETYPE_PLUGIN_SKILLS map is merged into the container.skill_ids param
 * in lib/chat/run-archetype-turn.ts alongside the pre-built skill IDs.
 *
 * Dynamic skill selection:
 * The Anthropic Skills API hard-caps container.skills at 8 items. Use
 * selectSkillsForMessage() rather than slicing the array directly — it pins
 * Edify-native skills and fills remaining slots by intent-matching vendored
 * skills against the user message. See intent-detection.ts for the categories.
 */

import type { ArchetypeSlug } from "@/lib/archetypes";
// Cast to Record so we can look up arbitrary plugin keys (e.g. "marketing/content-creation")
// without TypeScript complaining about missing properties on the initially-empty JSON.
// Each entry is an object { skill_id, hash, uploaded_at } — use .skill_id to extract the ID.
import uploadedIdsRaw from "../../../plugins/uploaded-ids.json";
import {
  EDIFY_NATIVE_SKILL_KEYS,
  VENDOR_TO_CATEGORY,
  detectIntentCategories,
  SKILL_CAP,
  type IntentCategory,
} from "./intent-detection";

// Re-export SKILL_CAP so run-archetype-turn.ts can import it from a single place.
export { SKILL_CAP };

const uploadedIds = uploadedIdsRaw as Record<
  string,
  { skill_id: string; hash: string; uploaded_at: string } | undefined
>;

/** Resolve a plugin key → skill_id string (or undefined if not yet uploaded). */
function resolve(key: string): string | undefined {
  return uploadedIds[key]?.skill_id;
}

/**
 * Reverse lookup: skill_id → plugin key (e.g. "skill_01..." → "design/social_card").
 * Built once at module load from uploaded-ids.json.
 */
const skillIdToKey: Record<string, string> = Object.fromEntries(
  (Object.entries(uploadedIds) as Array<[string, { skill_id: string } | undefined]>)
    .filter((entry): entry is [string, { skill_id: string }] => entry[1] !== undefined)
    .map(([key, value]) => [value.skill_id, key])
);

/**
 * Archetype → uploaded plugin skill_ids.
 *
 * Values are filtered at runtime: if a skill has not been uploaded yet (no entry
 * in uploaded-ids.json), it is silently excluded rather than sending an invalid ID.
 *
 * Follow-on sprints populate the other archetypes.
 */
export const ARCHETYPE_PLUGIN_SKILLS: Record<ArchetypeSlug, string[]> = {
  marketing_director: [
    resolve("marketing/content-creation"),
    resolve("marketing/campaign-plan"),
    resolve("marketing/draft-content"),
    resolve("marketing/brand-review"),
    resolve("design/design-critique"),
    resolve("design/canvas-design"),
    resolve("design/theme-factory"),
    resolve("design/social_card"),
    resolve("design/flyer"),
    resolve("design/donor_thank_you"),
    resolve("design/gala_invite"),
  ].filter(Boolean) as string[],

  executive_assistant: [
    resolve("operations/status-report"),
    resolve("operations/process-doc"),
    resolve("productivity/task-management"),
    resolve("sales/daily-briefing"),
    resolve("document/docx"),
    resolve("document/pptx"),
    resolve("document/internal-comms"),
    resolve("executive_assistant/board_meeting_packet"),
    resolve("executive_assistant/executive_brief"),
    resolve("executive_assistant/action_item_extractor"),
  ].filter(Boolean) as string[],
  events_director: [
    resolve("operations/status-report"),
    resolve("operations/risk-assessment"),
    resolve("operations/vendor-review"),
    resolve("sales/draft-outreach"),
    resolve("document/pptx"),
    resolve("document/xlsx"),
    resolve("events/run_of_show"),
    resolve("events/sponsor_package"),
    resolve("events/post_event_report"),
  ].filter(Boolean) as string[],
  development_director: [
    resolve("sales/account-research"),
    resolve("sales/call-prep"),
    resolve("data/analyze"),
    resolve("operations/status-report"),
    resolve("document/docx"),
    resolve("document/xlsx"),
    resolve("document/pptx"),
    resolve("development/grant_proposal_writer"),
    resolve("development/donor_stewardship_sequence"),
    resolve("development/impact_report"),
  ].filter(Boolean) as string[],
  programs_director: [
    resolve("operations/process-doc"),
    resolve("operations/status-report"),
    resolve("data/analyze"),
    resolve("data/build-dashboard"),
    resolve("document/docx"),
    resolve("document/xlsx"),
    resolve("programs/logic_model_builder"),
    resolve("programs/participant_survey"),
    resolve("programs/grant_outcome_report"),
  ].filter(Boolean) as string[],
  hr_volunteer_coordinator: [
    resolve("human-resources/onboarding"),
    resolve("human-resources/interview-prep"),
    resolve("human-resources/performance-review"),
    resolve("human-resources/policy-lookup"),
    resolve("human-resources/comp-analysis"),
    resolve("human-resources/volunteer_recruitment_kit"),
    resolve("human-resources/recognition_program"),
    resolve("human-resources/volunteer_handbook_section"),
    resolve("document/docx"),
    resolve("document/xlsx"),
  ].filter(Boolean) as string[],
};

/**
 * Select up to `cap` skill_ids for a single archetype turn using priority-based
 * dynamic selection.
 *
 * Strategy:
 *   1. Pin all Edify-native skill_ids (always sent — nonprofit differentiation).
 *   2. Score each vendored skill_id by whether its intent category matches the
 *      user message:
 *        - Score 2: category matched in user message
 *        - Score 1: no categories matched at all (neutral fallback)
 *        - Score 0: other categories matched but not this one
 *   3. Stable-sort vendored by score desc (ties preserve original array order).
 *   4. Fill remaining slots (cap - native count) from top-scored vendored skills.
 *
 * @param archetype  The archetype slug for this turn.
 * @param userMessage  The raw user message (temporal prefix not needed here).
 * @param cap  Maximum skills to return (defaults to SKILL_CAP = 8).
 * @returns  Array of skill_ids, length <= cap.
 */
export function selectSkillsForMessage(
  archetype: ArchetypeSlug,
  userMessage: string,
  cap: number = SKILL_CAP,
): string[] {
  const eligibleSkillIds = ARCHETYPE_PLUGIN_SKILLS[archetype] ?? [];

  // Partition into native (always pinned) and vendored (intent-scored).
  const nativeIds: string[] = [];
  type VendoredEntry = { skill_id: string; category: IntentCategory | undefined; originalIndex: number };
  const vendoredEntries: VendoredEntry[] = [];

  for (let i = 0; i < eligibleSkillIds.length; i++) {
    const skill_id = eligibleSkillIds[i];
    const key = skillIdToKey[skill_id];
    if (key && EDIFY_NATIVE_SKILL_KEYS.has(key)) {
      nativeIds.push(skill_id);
    } else {
      const category = key ? VENDOR_TO_CATEGORY[key] : undefined;
      vendoredEntries.push({ skill_id, category, originalIndex: i });
    }
  }

  // Score each vendored entry by intent match then stable-sort desc.
  const matchedCategories = detectIntentCategories(userMessage);
  const anyMatch = matchedCategories.size > 0;

  const scored: Array<VendoredEntry & { score: number }> = vendoredEntries.map((entry) => ({
    ...entry,
    score: !anyMatch ? 1
      : entry.category && matchedCategories.has(entry.category) ? 2
      : 0,
  }));

  scored.sort((a, b) => b.score - a.score || a.originalIndex - b.originalIndex);

  // Defensively cap natives (current archetypes never exceed 8 native skills, but handle it).
  const pinnedNatives = nativeIds.slice(0, cap);
  const vendorSlots = cap - pinnedNatives.length;
  const selectedVendored = scored.slice(0, vendorSlots).map((e) => e.skill_id);

  return [...pinnedNatives, ...selectedVendored];
}
